### ISSUE TITLE
Redirect from http to https either not in place or not working

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#144]
See title, tested with Firefox 45 and chrome 50. 

Entering https://www.freenode.net  manually works, cache doesn't seem to be in place, can't see anything in the headers that looks like a redirect to https.

**Comment by svbeon** [comment]
Well this should be on cloudflare's side alternatively a snippet of js:
```js
    if (window.location.protocol != "https:")
        window.location.href = "https:" + window.location.href.substring(window.location.protocol.length);
```

**Comment by edk0** [comment]
This is definitely a cloudflare issue, please don't do it with js

**Comment by svbeon** [comment]
@edk0 i just pointed out the options, but as i said it SHOULD definitely be a cloudflare issue

**Comment by svbeon** [comment]
Oh and btw this is really simple to fix @ cloudflare, just set a page rule

**Comment by svbeon** [comment]
After discussions long ago we said we didn't want to redirect to https, or add HSTS because we don't want to give people the false impression that they're using a secure site,  because `github<->cloudflare` is plaintext. 

Do we still want there to be a https redirect? If so we should poke @tomaw or someone else at infra

**Comment by emersonveenstra** [comment]
HTTPS is now forced and correctly redirecting
