### ISSUE TITLE
Content: Lack of information about nickserv's VACATION

### ISSUE THREAD

**Issue by Fuchs** [freenode/web-7.0#162]
Nickserv's help mentions VACATION  (extending the nick expiry time), http://freenode.net/policies doesn't, so whatever of the two is true with new policies should be put into either nickserv help or the policy page

**Comment by tinyhippw** [comment]
I disagree that this needs to be documented - for the vast majority of users, the explanation of the nick expiry policy is adequate - for those that are concerned about the expiry of their nick, should they be planning to leave for a while (due to vacation or illness or other), they could easily reach out to staff, or in #freenode, which I'd want to encourage, over linking to documentation

**Comment by Fuchs** [comment]
What are the downsides of documenting it? The downsides of _not_ documenting it are: 

- People think a nick is expired and then are let down, it is nowhere to be documented, so this looks like arbitrariness from the staffer in question, which leads to unhappy / angry users
- Someone who leaves might not be able to contact staff (as, especially on weekends, there are hours with no staff around) so that user reads the documentation, but finds nothing

**Comment by mistohise** [comment]
Vacation is a barely used option that increases the length of time for mechanical expiry by some amount, and increases the length of time before we'd likely drop an account by an essentially infinite amount.  As such, if we documented it at all it'd be some random intangible nonsense a bit like I've put here.  It certainly does not belong within policy docs. Closing off.
